import streamlit as st
import requests
import pandas as pd

# This is the Page Configuration step:
st.set_page_config(page_title="Network Copilot", page_icon="🛰️", layout="wide")

st.title(" Network Copilot Dashboard")
st.markdown("---")


# When running in Docker, use the service name 'backend' defined in docker-compose.yml
# When running locally (outside Docker), we would use 'localhost'
API_BASE_URL = "http://backend:8000" 

# This is the Sidebar for Real-Time Metrics & Controls
st.sidebar.header("Live Telemetry")

def get_live_data():
    try:
        # UPDATED: Changed localhost to backend
        response = requests.post(f"{API_BASE_URL}/chat", json={"question": "status"}, timeout=5)
        return response.json()
    except Exception as e:
        # Printing the error to the logs helps for debugging
        print(f"Connection Error: {e}")
        return None

data = get_live_data()

if data and data.get("status") == "success":
    metrics = data["network_health"]
    status_label = data.get("status_label", "Healthy")
    
    # Implementation of the Dynamic Status Label in Sidebar
    if status_label == "Healthy":
        st.sidebar.success(f"Current Status: {status_label}")
    elif status_label == "Degraded":
        st.sidebar.warning(f"Current Status: {status_label}")
    else:
        st.sidebar.error(f"Current Status: {status_label}")

    # Refresh Button
    if st.sidebar.button(" Refresh Telemetry"):
        st.rerun()

    # Download Diagnostic Report
    report_text = f"""
    NETWORK DIAGNOSTIC REPORT
    =========================
    Status: {status_label}
    Latency: {round(metrics.get('latency_ms', 0), 2)} ms
    Bandwidth: {round(metrics.get('bandwidth_mbps', 0), 2)} Mbps
    Packet Loss: {round(metrics.get('packet_loss_rate', 0), 2)} %
    -------------------------
    Generated by Network-copilot AI
    """
    st.sidebar.download_button(
        label=" Download Report",
        data=report_text,
        file_name="network_diagnostics.txt",
        mime="text/plain"
    )

    # Visual Status Cards
    col1, col2, col3 = st.columns(3)
    col1.metric("Latency", f"{round(metrics.get('latency_ms', 0), 2)} ms")
    col2.metric("Bandwidth", f"{round(metrics.get('bandwidth_mbps', 0), 2)} Mbps")
    col3.metric("Packet Loss", f"{round(metrics.get('packet_loss_rate', 0), 2)} %")

else:
    st.error("Could not connect to the Network Copilot API. Ensure the backend container is running.")

st.markdown("---")

# This is the Chat Interface
st.subheader("Chat with your Network")
if "messages" not in st.session_state:
    st.session_state.messages = []

# It Display's the chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Here We implement AI reaction logic
if prompt := st.chat_input("How is my network performing?"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Call the Backend API
    with st.chat_message("assistant"):
        try:
            # Here Changed localhost to backend (dockerization)
            res = requests.post(f"{API_BASE_URL}/chat", json={"question": prompt}, timeout=10)
            if res.status_code == 200:
                answer = res.json()["answer"]
                st.markdown(answer)
                st.session_state.messages.append({"role": "assistant", "content": answer})
            else:
                st.markdown("The backend responded with an error.")
        except Exception as e:
            st.markdown(f"I'm having trouble reaching the brain. Error: {e}")