import streamlit as st
import requests
import pandas as pd

# This is the Page Configuration step:
st.set_page_config(page_title="Network Copilot", page_icon="🛰️", layout="wide")

st.title(" Network Copilot Dashboard")
st.markdown("---")

# This is the Sidebar for Real-Time Metrics & Controls
st.sidebar.header("Live Telemetry")

def get_live_data():
    try:
        # Here it Calls the FastAPI backend
        response = requests.post("http://localhost:8000/chat", json={"question": "status"})
        return response.json()
    except:
        return None

data = get_live_data()

if data and data["status"] == "success":
    metrics = data["network_health"]
    status_label = data.get("status_label", "Healthy")
    
    # Here i implemented the Dynamic Status Label in Sidebar
    if status_label == "Healthy":
        st.sidebar.success(f"Current Status: {status_label}")
    elif status_label == "Degraded":
        st.sidebar.warning(f"Current Status: {status_label}")
    else:
        st.sidebar.error(f"Current Status: {status_label}")

    #  here the Refresh Button
    if st.sidebar.button(" Refresh Telemetry"):
        st.rerun()

    # This code block help to Download Diagnostic Report
    report_text = f"""
    NETWORK DIAGNOSTIC REPORT
    =========================
    Status: {status_label}
    Latency: {round(metrics.get('latency_ms', 0), 2)} ms
    Bandwidth: {round(metrics.get('bandwidth_mbps', 0), 2)} Mbps
    Packet Loss: {round(metrics.get('packet_loss_rate', 0), 2)} %
    -------------------------
    Generated by Network-copilot AI
    """
    st.sidebar.download_button(
        label=" Download Report",
        data=report_text,
        file_name="network_diagnostics.txt",
        mime="text/plain"
    )

    #  Visual Status Cards -- It will be seen (Top of Page)
    col1, col2, col3 = st.columns(3)
    col1.metric("Latency", f"{round(metrics.get('latency_ms', 0), 2)} ms")
    col2.metric("Bandwidth", f"{round(metrics.get('bandwidth_mbps', 0), 2)} Mbps")
    col3.metric("Packet Loss", f"{round(metrics.get('packet_loss_rate', 0), 2)} %")

else:
    st.error("Could not connect to the Network Copilot API. Ensure main.py is running.")

st.markdown("---")

#  This is my Chat Interface
st.subheader("Chat with your Network")
if "messages" not in st.session_state:
    st.session_state.messages = []

# Here it Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

#  Here we can see the AI reaction (React to user input)
if prompt := st.chat_input("How is my network performing?"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Here we Call the Backend API
    with st.chat_message("assistant"):
        try:
            res = requests.post("http://localhost:8000/chat", json={"question": prompt})
            answer = res.json()["answer"]
            st.markdown(answer)
            st.session_state.messages.append({"role": "assistant", "content": answer})
        except:
            st.markdown("I'm having trouble reaching the brain. Is the API server running?")