import streamlit as st
import requests
import pandas as pd
import sqlite3

# This is the Page Configuration step:
st.set_page_config(page_title="Network Copilot", layout="wide")

st.title("Network Copilot Dashboard")
st.markdown("---")

# API Configuration
# When running in Docker, use the service name 'backend'
# When running locally, use 'localhost'
API_BASE_URL = "http://backend:8000" 

# This is the block of code: Function to load persistent history from SQLite ---
def load_chat_history():
    """Retrieves all previous messages from the database to ensure persistence."""
    try:
        conn = sqlite3.connect("data/network_ops.db")
        # here we Pulls user_query and ai_response and formats them for the Streamlit chat UI
        query = "SELECT user_query, ai_response FROM chat_history ORDER BY rowid ASC"
        df = pd.read_sql_query(query, conn)
        conn.close()
        
        history = []
        for _, row in df.iterrows():
            history.append({"role": "user", "content": row['user_query']})
            history.append({"role": "assistant", "content": row['ai_response']})
        return history
    except Exception as e:
        print(f"History Load Error: {e}")
        return []

# This is the Sidebar for Real-Time Metrics & Controls
st.sidebar.header("Live Telemetry")

def get_live_data():
    try:
        response = requests.post(f"{API_BASE_URL}/chat", json={"question": "status"}, timeout=5)
        return response.json()
    except Exception as e:
        print(f"Connection Error: {e}")
        return None

data = get_live_data()

if data and data.get("status") == "success":
    metrics = data["network_health"]
    status_label = data.get("status_label", "Healthy")
    
    # Implementation of the Dynamic Status Label in Sidebar
    if status_label == "Healthy":
        st.sidebar.success(f"Current Status: {status_label}")
    elif status_label == "Degraded":
        st.sidebar.warning(f"Current Status: {status_label}")
    else:
        st.sidebar.error(f"Current Status: {status_label}")

    # Refresh Button
    if st.sidebar.button(" Refresh Telemetry"):
        st.rerun()

    # here, the code is implemented to Download Diagnostic Report
    report_text = f"""
    NETWORK DIAGNOSTIC REPORT
  *****************************
    Status: {status_label}
    Latency: {round(metrics.get('latency_ms', 0), 2)} ms
    Bandwidth: {round(metrics.get('bandwidth_mbps', 0), 2)} Mbps
    Packet Loss: {round(metrics.get('packet_loss_rate', 0), 2)} %
    -------------------------
    Generated by Network-copilot AI
    """
    st.sidebar.download_button(
        label="📥 Download Report",
        data=report_text,
        file_name="network_diagnostics.txt",
        mime="text/plain"
    )

    # Visual Status Cards
    col1, col2, col3 = st.columns(3)
    col1.metric("Latency", f"{round(metrics.get('latency_ms', 0), 2)} ms")
    col2.metric("Bandwidth", f"{round(metrics.get('bandwidth_mbps', 0), 2)} Mbps")
    col3.metric("Packet Loss", f"{round(metrics.get('packet_loss_rate', 0), 2)} %")

else:
    st.error("Could not connect to the Network Copilot API. Ensure the backend container is running.")

st.markdown("---")

# This is the Persistent Chat Interface
st.subheader("Chat with your Network")

# I am trying to refactor this code block to save the chat history, 
#  Initialize session state from Database instead of an empty list
if "messages" not in st.session_state:
    st.session_state.messages = load_chat_history()

# here i want to the Display the chat history, still working in this area
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# here i implemented the AI reaction logic
if prompt := st.chat_input("How is my network performing?"):
    # Add user message to UI
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # from here we Call the Backend API
    with st.chat_message("assistant"):
        try:
            res = requests.post(f"{API_BASE_URL}/chat", json={"question": prompt}, timeout=10)
            if res.status_code == 200:
                answer = res.json()["answer"]
                st.markdown(answer)
                # Store the new response in session state (it was already saved to DB by the backend)
                st.session_state.messages.append({"role": "assistant", "content": answer})
            else:
                st.markdown("The backend responded with an error.")
        except Exception as e:
            st.markdown(f"I'm having trouble reaching the brain. Error: {e}")